import type { Product, Category } from "@/types";

/** Sample data so design is visible without backend */
export const SAMPLE_CATEGORIES: Category[] = [
  { id: "c1", name: "হোম ডেকর", slug: "home-decor" },
  { id: "c2", name: "নকশি ও টেক্সটাইল", slug: "nakshi-textile" },
  { id: "c3", name: "জুট ও পাট", slug: "jute" },
  { id: "c4", name: "সিরামিক ও মাটি", slug: "ceramic" },
  { id: "c5", name: "উপহার সেট", slug: "gift-sets" },
  { id: "c6", name: "লাইফস্টাইল", slug: "lifestyle" },
];

const img = (id: string, w = 600, h = 750) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "হাতে বোনা নকশি কাঁথা থ্রো",
    slug: "nakshi-kantha-throw",
    shortDescription: "ঐতিহ্যবাহী নকশি সেলাই, নরম তুলার কাপড়।",
    regularPrice: 2800,
    salePrice: 2390,
    stockQuantity: 12,
    material: "তুলা",
    isHandmade: true,
    isPremium: true,
    isFeatured: true,
    category: SAMPLE_CATEGORIES[1],
    images: [{ id: "i1", url: img("photo-1601925260368-ae2f83cf8b7f"), isPrimary: true }],
  },
  {
    id: "p2",
    name: "প্রাকৃতিক জুট স্টোরেজ বাস্কেট",
    slug: "jute-storage-basket",
    shortDescription: "মজবুত পাটের তৈরি, ঘর সাজানোর জন্য।",
    regularPrice: 950,
    salePrice: null,
    stockQuantity: 25,
    material: "জুট",
    isHandmade: true,
    isFeatured: true,
    category: SAMPLE_CATEGORIES[2],
    images: [{ id: "i2", url: img("photo-1595428774223-ef52624120d2"), isPrimary: true }],
  },
  {
    id: "p3",
    name: "টেরা কোটা প্ল্যান্টার সেট",
    slug: "terra-cotta-planter-set",
    shortDescription: "মাটির তৈরি ৩ পিসের মিনি প্ল্যান্টার।",
    regularPrice: 1200,
    salePrice: 990,
    stockQuantity: 18,
    material: "মাটি",
    isHandmade: true,
    isFeatured: true,
    category: SAMPLE_CATEGORIES[3],
    images: [{ id: "i3", url: img("photo-1485955900006-10f4d324d411"), isPrimary: true }],
  },
  {
    id: "p4",
    name: "হাতের কাজের ম্যাক্রামে ওয়াল হ্যাঙ্গিং",
    slug: "macrame-wall-hanging",
    shortDescription: "বোহো স্টাইল, প্রাকৃতিক সুতা।",
    regularPrice: 1850,
    salePrice: null,
    stockQuantity: 8,
    material: "তুলা সুতা",
    isHandmade: true,
    isPremium: true,
    isFeatured: true,
    category: SAMPLE_CATEGORIES[0],
    images: [{ id: "i4", url: img("photo-1616046229478-9901c5536a45"), isPrimary: true }],
  },
  {
    id: "p5",
    name: "বাঁশের চা সেট (৪ কাপ)",
    slug: "bamboo-tea-set",
    shortDescription: "হালকা বাঁশের তৈরি, উপহারের জন্য আদর্শ।",
    regularPrice: 1600,
    salePrice: 1450,
    stockQuantity: 15,
    material: "বাঁশ",
    isHandmade: true,
    isFeatured: false,
    category: SAMPLE_CATEGORIES[5],
    images: [{ id: "i5", url: img("photo-1571934811356-5cc061b6821f"), isPrimary: true }],
  },
  {
    id: "p6",
    name: "লিনেন কুশন কভার সেট",
    slug: "linen-cushion-covers",
    shortDescription: "ন্যাচারাল লিনেন, ২ পিস সেট।",
    regularPrice: 1100,
    salePrice: null,
    stockQuantity: 30,
    material: "লিনেন",
    isHandmade: false,
    isFeatured: true,
    category: SAMPLE_CATEGORIES[1],
    images: [{ id: "i6", url: img("photo-1584100936595-c0654b55a6e2"), isPrimary: true }],
  },
  {
    id: "p7",
    name: "হাতে তৈরি মোমবাতি সেট",
    slug: "handmade-candle-set",
    shortDescription: "সয়া মোম, ল্যাভেন্ডার ও সিডার উড সুগন্ধ।",
    regularPrice: 890,
    salePrice: 750,
    stockQuantity: 40,
    material: "সয়া মোম",
    isHandmade: true,
    isFeatured: true,
    category: SAMPLE_CATEGORIES[4],
    images: [{ id: "i7", url: img("photo-1602607620672-6cfd5e5c8e6e"), isPrimary: true }],
  },
  {
    id: "p8",
    name: "উডেন সার্ভিং ট্রে",
    slug: "wooden-serving-tray",
    shortDescription: "শেগুন কাঠ, মিনিমাল ফিনিশ।",
    regularPrice: 2200,
    salePrice: null,
    stockQuantity: 6,
    material: "শেগুন",
    isHandmade: true,
    isPremium: true,
    isFeatured: false,
    category: SAMPLE_CATEGORIES[0],
    images: [{ id: "i8", url: img("photo-1595428774223-ef52624120d2"), isPrimary: true }],
  },
];
